### ISSUE TITLE
[PE-D][Tester A] 'Clear' commands clear everything immediately after user input 'clear'

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W16-2/tp#251]
Would it be better if the user got a clear confirmation message asking them if they really wanted to clear all data? That might help guard against users who accidentally input the 'clear' command.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Choonyan02/ped#1

**Comment by yucongkoo** [comment]
My suggestion to this is we remove this feature, as it is not a planned feature by us, rather inherited from AB3. 

Reasoning:

Considering the case where users will actually clear the whole address book is relatively rare, I think this feature is less important. On top of that, we can include in our UG on how to clear the address(by manually polluting the data file) so that when they plan to do so, they got workarounds.

**Comment by songfangyl** [comment]
I agree to remove, but do we allow to remove feature in v1.4?

**Comment by yucongkoo** [comment]
Will be including this in planned enhancements
