### ISSUE TITLE
[PE-D][Tester D] Appointments in the past

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W16-2/tp#276]
Just a consistency thing that your group can take into consideration. As you are not allowed to create appointments in the past with `d/` but you can create still appointments in the past in terms of `t/`

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: dishenggg/ped#3

**Comment by yucongkoo** [comment]
I believe you explained to us about this decision choice before right?

**Comment by Jweewee** [comment]
Correct, here is a realistic scenario: 
A user may need to mark sales appointments that occurred earlier on the same day but missed the data entry process as  sales appointments may be dynamic.
Hence there is a need for flexibility to add appointments that occurred earlier in the day due to changes in schedules or unexpected meetings, and then mark it.

 Allowing appointments with past times on the current day caters to this common scenario.
